# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCMwg29tCfIBCN8P63Tlrrp_HRYHwd8L
"""

import cmath
a=float(input('enter a:'))
b=float(input('enter b:'))
c=float(input('enter c:'))
x=float(input('enter x:'))
y=(a*x*x)+(b*x)+c
print("for the values of",a,"",b,"","",c,"y is:",y)