# -*- coding: utf-8 -*-
"""v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCMwg29tCfIBCN8P63Tlrrp_HRYHwd8L
"""

a=5
b-4
c=6
x=4.5
y=(a*x*x)+(b*x)+c
print("for the values of",a,"",b,"","",c,"y is:",y)